// ProCounsel Page Color Palette
export const BACKGROUND_DARK = '#1a1a2e';
export const PRIMARY_INDIGO = '#818cf8';
export const ACCENT_GREEN = '#34d399';
export const ACCENT_GREEN_DARK = '#10b981';
export const ACCENT_YELLOW = '#fbbf24';
export const ACCENT_YELLOW_DARK = '#f59e0b';
export const OBSTACLE_RED = '#f87171';
export const OBSTACLE_RED_DARK = '#ef4444';
export const OBSTACLE_YELLOW = '#fbbf24';
export const OBSTACLE_YELLOW_DARK = '#f59e0b';
export const OBSTACLE_BLUE = '#60a5fa';
export const OBSTACLE_BLUE_DARK = '#3b82f6';
export const OBSTACLE_PURPLE = '#a78bfa';
export const OBSTACLE_PURPLE_DARK = '#8b5cf6';
export const STUDENT_CYAN = '#00ffff';
export const WHITE = '#ffffff';
export const GOLD = 'gold';
